server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    zipkin: http://localhost:9411

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${AMBERO_SSAC_BD_HOST}:${AMBERO_SSAC_BD_PORT}/${AMBERO_SSAC_BD_NAME}
    platform: postgres
    username: ${AMBERO_SSAC_BD_USERNAME}
    password: ${AMBERO_SSAC_BD_PASSWORD}
    continue-on-error: true

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
      SQL: debug
    database: postgresql

jwt:
  secret: TSABRWZQKMTVDBFBFVQUYQLEOBEONIPLCEVRZEPUWR9HVZYTEZBPLEBFZFVILCYVNWZCPLFBEDGEMEYVBDOQWAINYW

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"