server:
  port: 8085

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shamirtv1/ambero
          search-paths: config-data
          default-label: master
  security:
    user:
      name: root
      password: s3cr3t

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"